server:
  port: "8080"
  mode: "debug"

database:
  host: "localhost"
  user: "postgres"
  password: "postgres"
  dbname: "postgres"
  port: "5432"
  sslmode: "disable"
  timezone: "Asia/Shanghai"

jwt:
  secret: "your_super_secret_key"
  expire: 24
